services:
  product-service_postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - product-service

#  product-service_mongo:
#    image: mongo:8.0
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    restart: unless-stopped
#    healthcheck:
#      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
#      interval: 2s
#      timeout: 10s
#      retries: 5
#    volumes:
#      - mongo-data:/data/db
#    networks:
#      - product-service

  product-service:
    build:
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_URL=product-service_postgres
      - MONGO_URL=product-service_mongo
    depends_on:
      product-service_postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
#      product-service_mongo:
#        condition: service_healthy
    tty: true
    networks:
      - product-service
      - backend
      - analytics
    labels:
      - "traefik.http.routers.product-service.rule=HostRegexp(`api\\..+`) && PathPrefix(`/product`)"


networks:
  product-service:

volumes:
  postgres-data:
  mongo-data: