FROM python:3.13-alpine
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV ENV production

WORKDIR /product-service

RUN apk add --no-cache patch
RUN pip install --no-cache poetry

COPY . .
RUN poetry install --no-dev

WORKDIR /usr/local/lib/python3.13/site-packages
RUN patch -p1 < /product-service/patches/strawberry-sqlalchemy.patch

WORKDIR /product-service
EXPOSE 8000
CMD [ "poetry", "run", "gunicorn", "src.main:app", "--bind", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker" ]
