"""Populate data

Revision ID: 82430fd6dda8
Revises: d2af1c2675bc
Create Date: 2025-04-06 01:52:44.371635

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "82430fd6dda8"
down_revision: Union[str, None] = "d2af1c2675bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Populating data")
    with open("migrations/inserts.sql", "r") as f:
        for line in f.readlines():
            op.execute(text(line))
    print("Data populated")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE productmodel CASCADE")
    # ### end Alembic commands ###
