"""Initial migration

Revision ID: d2af1c2675bc
Revises:
Create Date: 2025-04-06 01:09:18.610637

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d2af1c2675bc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productmodel",
        sa.Column("ean", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generic_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nutrition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "nutri_score",
            sa.Enum(
                "A", "B", "C", "D", "E", "UNKNOWN", "NOT_APPLICABLE", name="nutriscore"
            ),
            nullable=False,
        ),
        sa.Column("ingredients", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.TEXT()), nullable=True),
        sa.Column("images", postgresql.ARRAY(sa.TEXT()), nullable=True),
        sa.Column("brand_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("ean"),
    )

    # INSERT INTO product (ean, name, generic_name, nutri_score, ingredients, quantity, unit, keywords, images, nutrition, category_name)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("productmodel")
    # ### end Alembic commands ###
