services:
  serviceName_postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - serviceName

#  serviceName_mongo:
#    image: mongo:8.0
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    restart: unless-stopped
#    healthcheck:
#      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
#      interval: 2s
#      timeout: 10s
#      retries: 5
#    volumes:
#      - mongo-data:/data/db
#    networks:
#      - serviceName

  serviceName:
    build:
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_URL=serviceName_postgres
      - MONGO_URL=serviceName_mongo
    depends_on:
      serviceName_postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
#      serviceName_mongo:
#        condition: service_healthy
    tty: true
    networks:
      - serviceName
      - backend
      - analytics
    labels:
      - "traefik.http.routers.serviceName.rule=HostRegexp(`api\\..+`) && PathPrefix(`/kebab`)"


networks:
  serviceName:

volumes:
  postgres-data:
  mongo-data: